import express from "express";
import { requireAuth } from "../middleware/auth.js";
import * as c from "../controllers/researchController.js";
const r = express.Router();
r.use(requireAuth);
r.post("/", c.createResearch);
r.get("/", c.listResearch);
r.get("/:id/events", c.events);
r.get("/:id/sources", c.getSources);
r.get("/:id/evidence", c.getEvidence);
r.get("/:id/claims", c.getClaims);
r.get("/:id/gaps", c.getGaps);
r.get("/:id/conflicts", c.getConflicts);
r.get("/:id/report", c.getReport);
r.get("/:id/export-pdf", c.exportPdf);
r.post("/:id/export-pdf", c.exportPdf);
r.get("/:id/evaluation", c.getEvaluation);
r.get("/:id", c.getResearch);
r.delete("/:id", c.deleteResearch);
r.post("/:id/start", c.startResearch);
r.post("/:id/stop", c.stopResearch);
r.post("/:id/refine", c.refineResearch);
export default r;
